"use client";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
// or `v1X-appRouter` if you are using Next.js v1X

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme";
import { usePathname } from "next/navigation";
import { CssBaseline } from "@mui/material";
import Navbar from "./components/Navbar";
import Footerbar from "./components/Footerbar";
import SocialMediaLinks from "./components/SocialMediaLinks";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Ai Art App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  console.log(pathname);

  const generateTitle = (path: string) => {
    if (path === "/") return "Home | Ai-Art-App";
    const formattedPath = path.replace("/", "").replace(/-/g, "").toLowerCase();
    return `${formattedPath} | Ai-Art-App`;
  };
  return (
    <html lang="en">
      <head>
        <title>{generateTitle(pathname)}</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          display: "flex",
          flexDirection: "column",
          minHeight: "100vh", // This ensures the body fills the entire height of the viewport
        }}
      >
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Navbar />
            <main style={{ flex: 1 }}>
              {/* This allows the content to grow and take up available space */}
              {children}
            </main>
            <SocialMediaLinks />
            <Footerbar />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
